name: Docs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Swift
        uses: SwiftyLab/setup-swift@v1
        with:
          swift-version: '6.2'

      - name: Generate DocC
        run: |
          swift package --allow-writing-to-directory docs \
            generate-documentation \
            --target JQ \
            --disable-indexing \
            --transform-for-static-hosting \
            --hosting-base-path jq \
            --output-path docs

      - name: Add 404 fallback for SPA routing
        run: cp docs/index.html docs/404.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          enable_jekyll: false
          force_orphan: true
